# -*- coding: utf-8 -*-
"""StreetSmarts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8qOxBirBMErYRU8vUjUrcc8n0qvKtbN
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("atlanta_city_posts.csv")

from transformers import BertTokenizer, BertForSequenceClassification
from transformers import pipeline

#finbert model
finbert = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone', num_labels = 3) #label = {positive, negative, neutral}
tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')

nlp = pipeline("sentiment-analysis", model = finbert, tokenizer = tokenizer)

print(df.columns)
print(df.post.to_list())

sentences = df.post.to_list()
result = nlp(sentences)

print(result[0])
print(result[0]["label"], result[0]["score"])

labels = []
sentiment_scores = []
for analysis in result:
  labels.append(analysis["label"])
  sentiment_scores.append(analysis["score"])

df["sentiment"] = labels
df["score"] = sentiment_scores

df.to_csv("atlanta_city_posts_sent_analysis.csv")
df.head